.TH "src/structures Directory Reference" 3 "Tue Sep 29 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/structures Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcubic\&.h\fP"
.br
.ti -1c
.RI "file \fBcustom\&.h\fP"
.br
.ti -1c
.RI "file \fBhexagonal\&.h\fP"
.br
.ti -1c
.RI "file \fBlattice\&.h\fP"
.br
.ti -1c
.RI "file \fBorthorhombic\&.h\fP"
.br
.ti -1c
.RI "file \fBstructure_lib\&.h\fP"
.br
.ti -1c
.RI "file \fBtetragonal\&.h\fP"
.br
.in -1c
