.TH "atom_t" 3 "Wed Sep 30 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atom_t \- x,y,z point defining the atomic coordinates, and a vector for each atoms nearest neighbors  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
x,y,z point defining the atomic coordinates, and a vector for each atoms nearest neighbors 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "int \fBtypeId\fP"
.br
.ti -1c
.RI "std::vector< int > \fBnaborIds\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::vector<int> atom_t::naborIds"

.SS "int atom_t::typeId"

.SS "double atom_t::x"

.SS "double atom_t::y"

.SS "double atom_t::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
