.TH "basis_t" 3 "Wed Sep 30 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basis_t \- x,y,z point defining the basis coordinates, and the element type  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
x,y,z point defining the basis coordinates, and the element type 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "int \fBtypeId\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int basis_t::typeId"

.SS "double basis_t::x"

.SS "double basis_t::y"

.SS "double basis_t::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
