.TH "Errors" 3 "Wed Sep 30 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Errors \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "\fBPurpose:\fP "
.PP
.PP
.PP
.nf
/*****************************************************************************\
/  Class to process different types of warnings, errors and usage info        \
/                                                                             \
/*****************************************************************************\
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Joseph M\&. Gonzalez
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1
.RE
.PP
\fBDate:\fP
.RS 4
Sep 13, 2015 19:16:20
.RE
.PP
\fBContact\fP 
.br
 jmgonza6@mail.usf.edu 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrors\fP ()"
.br
.ti -1c
.RI "\fB~Errors\fP ()"
.br
.ti -1c
.RI "void \fBkill\fP (const char *file, const char *subroutine, int line, const char *message)"
.br
.RI "\fIThrow a fatal error and kill the entire run\&. \fP"
.ti -1c
.RI "void \fBwarn\fP (const char *file, const char *subroutine, int line, const char *message)"
.br
.RI "\fIThrow a warning, print a message and continue on\&. \fP"
.ti -1c
.RI "void \fBshow_usage_info\fP (const char *funcName)"
.br
.RI "\fIShow a list of the possible parameters and operational modes of the program\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Errors::Errors ()"

.SS "Errors::~Errors ()"

.SH "Member Function Documentation"
.PP 
.SS "void Errors::kill (const char * file, const char * subroutine, int line, const char * message)"

.PP
Throw a fatal error and kill the entire run\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP - file in which error occured 
.br
\fIsubroutine\fP - subroutine throwing the error 
.br
\fIline\fP - line on which the error occured 
.br
\fImessage\fP - message to the user with the details of the error 
.RE
.PP

.SS "void Errors::show_usage_info (const char * funcName)"

.PP
Show a list of the possible parameters and operational modes of the program\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfuncName\fP - name of the calling function 
.RE
.PP

.SS "void Errors::warn (const char * file, const char * subroutine, int line, const char * message)"

.PP
Throw a warning, print a message and continue on\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP - file in which warning occured 
.br
\fIsubroutine\fP - subroutine throwing the warning 
.br
\fIline\fP - line on which the warning occured 
.br
\fImessage\fP - message to the user with the details of the warning 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
