.TH "src/gui/gui.h" 3 "Tue Sep 29 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/gui.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGui\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFRWIDTH\fP   600"
.br
.RI "\fIwidth of the frame inside each tab \fP"
.ti -1c
.RI "#define \fBFRHEIGHT\fP   400"
.br
.RI "\fIheight of the frame inside each tab \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FRHEIGHT   400"

.PP
height of the frame inside each tab 
.SS "#define FRWIDTH   600"

.PP
width of the frame inside each tab 
.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
