.TH "Line" 3 "Wed Sep 30 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- x,y,z point defining two vertices, used for drawing the unit cell  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
x,y,z point defining two vertices, used for drawing the unit cell 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBv\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPoint\fP Line::v[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
