.TH "Memory" 3 "Sun Oct 4 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "\fBPurpose:\fP "
.PP
.PP
.PP
.nf
/********************************************************************************\
/  Template based memory managment class for use in allocating/deallocating      \
/  blocks of memory using new[]                                                  \
/                                                                                \
/********************************************************************************\
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Joseph M\&. Gonzalez
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1
.RE
.PP
\fBDate:\fP
.RS 4
May 28, 2015 19:16:20
.RE
.PP
\fBContact\fP 
.br
 jmgonza6@mail.usf.edu 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemory\fP ()"
.br
.ti -1c
.RI "\fB~Memory\fP ()"
.br
.ti -1c
.RI "template<typename retVal > retVal * \fBnew_1d\fP (int length)"
.br
.RI "\fITemplate to create a 1D array using \fB\fCnew\fP\fP \fP"
.ti -1c
.RI "template<typename TYPE > void \fBdestroy\fP (TYPE *array)"
.br
.RI "\fISafe method of deleting memory allocations\&. \fP"
.ti -1c
.RI "template<typename retVal > retVal ** \fBnew_2d\fP (int rows, int columns)"
.br
.RI "\fITemplate to create a 2D array using \fB\fCnew\fP\fP \fP"
.ti -1c
.RI "template<typename TYPE > void \fBdestroy\fP (TYPE **array)"
.br
.RI "\fISafe method of deleting memory allocations\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Memory::Memory ()\fC [inline]\fP"

.SS "Memory::~Memory ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename TYPE > void Memory::destroy (TYPE * array)\fC [inline]\fP"

.PP
Safe method of deleting memory allocations\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIarray\fP - 1D array created by new_1d or using \fB\fCnew\fP\fP 
.RE
.PP

.SS "template<typename TYPE > void Memory::destroy (TYPE ** array)\fC [inline]\fP"

.PP
Safe method of deleting memory allocations\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIarray\fP - 2D array created by new_2d or using \fB\fCnew\fP\fP 
.RE
.PP

.SS "template<typename retVal > retVal* Memory::new_1d (int length)\fC [inline]\fP"

.PP
Template to create a 1D array using \fB\fCnew\fP\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIarray\fP - Address of array to be allocated 
.br
\fIlength\fP - Length of array 
.RE
.PP
\fBReturns:\fP
.RS 4
1D array of type \fB\fCTYPE\fP\fP 
.RE
.PP

.SS "template<typename retVal > retVal** Memory::new_2d (int rows, int columns)\fC [inline]\fP"

.PP
Template to create a 2D array using \fB\fCnew\fP\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIarray\fP - Address of array to be allocated 
.br
\fIrows\fP - Number of rows in array 
.br
\fIcolumns\fP - Number of columns in array 
.RE
.PP
\fBReturns:\fP
.RS 4
2D array of type \fB\fCTYPE\fP\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
