.TH "PeriodicTable" 3 "Sun Oct 4 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeriodicTable \- A structure containing strings representing up to element 110 and their associated masses in AMU\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A structure containing strings representing up to element 110 and their associated masses in AMU\&. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBelements\fP [110]"
.br
.ti -1c
.RI "double \fBamu\fP [110]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double PeriodicTable::amu[110]"

.SS "std::string PeriodicTable::elements[110]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
