.TH "Point" 3 "Tue Sep 29 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- x,y,z coordinates for a point in space  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
x,y,z coordinates for a point in space 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP [3]"
.br
.ti -1c
.RI "float \fBn\fP [3]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float Point::n[3]"

.SS "float Point::x[3]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
