.TH "Reader" 3 "Wed Sep 30 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reader \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "\fBPurpose:\fP "
.PP
.PP
.PP
.nf
/********************************************************************************\
/  Class for reading crystal parameters from a file                              \
/                                                                                \
/********************************************************************************\
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Joseph M\&. Gonzalez
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1
.RE
.PP
\fBDate:\fP
.RS 4
Sep 27, 2015 23:16:20
.RE
.PP
\fBContact\fP 
.br
 jmgonza6@mail.usf.edu 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReader\fP ()"
.br
.ti -1c
.RI "\fB~Reader\fP ()"
.br
.ti -1c
.RI "void \fBfile\fP (char *pf)"
.br
.ti -1c
.RI "int \fBinsane\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBalat\fP"
.br
.RI "\fIlatttice parameter a (Å) \fP"
.ti -1c
.RI "double \fBblat\fP"
.br
.RI "\fIlattice parameter b (Å) \fP"
.ti -1c
.RI "double \fBclat\fP"
.br
.RI "\fIlattice parameter c (Å) \fP"
.ti -1c
.RI "double \fBalpha\fP"
.br
.RI "\fIangle beteween c & b \fP"
.ti -1c
.RI "double \fBbeta\fP"
.br
.RI "\fIangle between c & a \fP"
.ti -1c
.RI "double \fBgamma\fP"
.br
.RI "\fIangle between a & b \fP"
.ti -1c
.RI "double \fBcta\fP"
.br
.RI "\fIc/a ratio, for use with \fBHexagonal()\fP, h-BN(), Graphene() \fP"
.ti -1c
.RI "int \fBlbasis\fP"
.br
.RI "\fInumber of basis atoms for graphene \fP"
.ti -1c
.RI "int \fBnx\fP"
.br
.RI "\fIsupercell dimension along x \fP"
.ti -1c
.RI "int \fBny\fP"
.br
.RI "\fIsupercell dimension along y \fP"
.ti -1c
.RI "int \fBnz\fP"
.br
.RI "\fIsupercell dimension along z \fP"
.ti -1c
.RI "int \fBfractional\fP"
.br
.RI "\fIfractional coordinates, 1 = true, 0 = false \fP"
.ti -1c
.RI "int \fBgraphene\fP"
.br
.RI "\fIgraphene structure was built, 1 = true, 0 = false \fP"
.ti -1c
.RI "int \fBcustom\fP"
.br
.RI "\fIa custom structure was built, 1 = true, 0 = false \fP"
.ti -1c
.RI "int \fBresets\fP"
.br
.RI "\fIreset count \fP"
.ti -1c
.RI "int \fBrun_count\fP"
.br
.RI "\fIrun count, for debugging \fP"
.ti -1c
.RI "int \fBquit\fP"
.br
.RI "\fIquit signal \fP"
.ti -1c
.RI "int \fBview\fP"
.br
.RI "\fIrender+build signal \fP"
.ti -1c
.RI "char * \fBpfile\fP"
.br
.RI "\fIparameter file to define the crystal \fP"
.ti -1c
.RI "char * \fBout_name\fP"
.br
.RI "\fIfile name to write \fP"
.ti -1c
.RI "char * \fBfile_format\fP"
.br
.RI "\fItype of file to write \fP"
.ti -1c
.RI "char * \fBbravais\fP"
.br
.RI "\fIwhich lattice ? \fP"
.ti -1c
.RI "char * \fBlstyle\fP"
.br
.RI "\fIbravais lattice style, BCC \fP"
.ti -1c
.RI "char * \fBpd_struct\fP"
.br
.RI "\fIdefines a library structure to use \fP"
.ti -1c
.RI "char * \fBelement\fP"
.br
.RI "\fIwhich species ? \fP"
.ti -1c
.RI "std::vector< std::string > \fBelemList\fP"
.br
.RI "\fIdefine a custom stoichiometry (C,H,N,O) \fP"
.ti -1c
.RI "std::vector< int > \fBelemCount\fP"
.br
.RI "\fIdefine a custom stoichiometry (2,4,1,3) \fP"
.ti -1c
.RI "std::vector< std::vector< double > > \fBcustomBasis\fP"
.br
.RI "\fIcontainer for defining a custom basis set \fP"
.ti -1c
.RI "std::string \fBcustomName\fP"
.br
.RI "\fIchemical formula of a custom structure \fP"
.ti -1c
.RI "\fBParser\fP * \fBparser\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Reader::Reader ()"

.SS "Reader::~Reader ()"

.SH "Member Function Documentation"
.PP 
.SS "void Reader::file (char * pf)"

.SS "int Reader::insane ()"

.SH "Field Documentation"
.PP 
.SS "double Reader::alat"

.PP
latttice parameter a (Å) 
.SS "double Reader::alpha"

.PP
angle beteween c & b 
.SS "double Reader::beta"

.PP
angle between c & a 
.SS "double Reader::blat"

.PP
lattice parameter b (Å) 
.SS "char* Reader::bravais"

.PP
which lattice ? 
.SS "double Reader::clat"

.PP
lattice parameter c (Å) 
.SS "double Reader::cta"

.PP
c/a ratio, for use with \fBHexagonal()\fP, h-BN(), Graphene() 
.SS "int Reader::custom"

.PP
a custom structure was built, 1 = true, 0 = false 
.SS "std::vector<std::vector<double> > Reader::customBasis"

.PP
container for defining a custom basis set 
.SS "std::string Reader::customName"

.PP
chemical formula of a custom structure 
.SS "std::vector<int> Reader::elemCount"

.PP
define a custom stoichiometry (2,4,1,3) 
.SS "char* Reader::element"

.PP
which species ? 
.SS "std::vector<std::string> Reader::elemList"

.PP
define a custom stoichiometry (C,H,N,O) 
.SS "char* Reader::file_format"

.PP
type of file to write 
.SS "int Reader::fractional"

.PP
fractional coordinates, 1 = true, 0 = false 
.SS "double Reader::gamma"

.PP
angle between a & b 
.SS "int Reader::graphene"

.PP
graphene structure was built, 1 = true, 0 = false 
.SS "int Reader::lbasis"

.PP
number of basis atoms for graphene 
.SS "char* Reader::lstyle"

.PP
bravais lattice style, BCC 
.SS "int Reader::nx"

.PP
supercell dimension along x 
.SS "int Reader::ny"

.PP
supercell dimension along y 
.SS "int Reader::nz"

.PP
supercell dimension along z 
.SS "char* Reader::out_name"

.PP
file name to write 
.SS "\fBParser\fP* Reader::parser"

.SS "char* Reader::pd_struct"

.PP
defines a library structure to use 
.SS "char* Reader::pfile"

.PP
parameter file to define the crystal 
.SS "int Reader::quit"

.PP
quit signal 
.SS "int Reader::resets"

.PP
reset count 
.SS "int Reader::run_count"

.PP
run count, for debugging 
.SS "int Reader::view"

.PP
render+build signal 

.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
