.TH "StructureLib" 3 "Sun Oct 4 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StructureLib \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "\fBPurpose:\fP "
.PP
.PP
.PP
.nf
/******************************************************************************\
/  Class to generate the basis atom positions, lattice vectors and lattice     \
/  parameters for various 2D materials  and Energetic materials, specifically, \
/  2D materials: Graphene, h-BN                                                \
/                MDC-2H/1T i.e.  (Pb,Sn)(S,Se,Te)2                             \
/                TMDC-2H/1T i.e. (Mo,W)(S,Se,Te)2                              \
/  Energetic materials: PETN-I, TATB, β-HMX                                    \
/                                                                              \
/  * * Inherits from the LATTICE class                                         \
/                                                                              \ 
/******************************************************************************\
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Joseph M\&. Gonzalez
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.3
.RE
.PP
\fBDate:\fP
.RS 4
Sep 13, 2015 19:16:20
.RE
.PP
\fBContact\fP 
.br
 jmgonza6@mail.usf.edu 
.PP
Inherits \fBLATTICE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStructureLib\fP (char i_lstyle[], int basisAtoms, double i_alat, double i_clat, std::vector< std::string > elements)"
.br
.RI "\fIConstructor for the graphene class when accessed from a gui session or when reading a parameters file\&. \fP"
.ti -1c
.RI "\fB~StructureLib\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBgraphene\fP (double i_alat, double i_clat, int basisAtoms)"
.br
.RI "\fIConstrct an hexagonal 2 atom unit cell or a 4 atom rectangular unit cell\&. \fP"
.ti -1c
.RI "void \fBh_bn\fP ()"
.br
.RI "\fIDefine the basis atoms and lattice for hexagonal Boron Nitride\&. \fP"
.ti -1c
.RI "void \fBmdc_2h\fP (double i_alat, double i_clat, std::vector< std::string > elements)"
.br
.RI "\fIDefine the basis atoms and lattice for a single layer of a metal dichalcogenide, 
.br
 i\&.e\&. (Pb,Sn)(S,Se,Te)2 in the 2H polytype\&. \fP"
.ti -1c
.RI "void \fBmdc_1t\fP (double i_alat, double i_clat, std::vector< std::string > elements)"
.br
.RI "\fIDefine the basis atoms and lattice for a single layer of a metal dichalcogenide, 
.br
 i\&.e\&. (Pb,Sn)(S,Se,Te)2 in the 1T polytype\&. \fP"
.ti -1c
.RI "void \fBtmdc_2h\fP (double i_alat, double i_clat, std::vector< std::string > elements)"
.br
.RI "\fIDefine the basis atoms and lattice for a single layer of a transition metal dichalcogenide, 
.br
 i\&.e\&. (Mo,W)(S,Se,Te)2 in the 2H polytype\&. \fP"
.ti -1c
.RI "void \fBtmdc_1t\fP (double i_alat, double i_clat, std::vector< std::string > elements)"
.br
.RI "\fIDefine the basis atoms and lattice for a single layer of a transition metal dichalcogenide, 
.br
 i\&.e\&. (Mo,W)(S,Se,Te)2 in the 1T polytype\&. \fP"
.ti -1c
.RI "void \fBpetn\fP ()"
.br
.RI "\fIDefine the basis atoms and lattice for a single crystal of PETN-I\&. \fP"
.ti -1c
.RI "void \fBtatb\fP ()"
.br
.RI "\fIDefine the basis atoms and lattice for a single crystal of TATB\&. \fP"
.ti -1c
.RI "void \fBhmx\fP ()"
.br
.RI "\fIDefine the basis atoms and lattice for a single crystal of HMX\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBcta\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StructureLib::StructureLib (char i_lstyle[], int basisAtoms, double i_alat, double i_clat, std::vector< std::string > elements)"

.PP
Constructor for the graphene class when accessed from a gui session or when reading a parameters file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi_lstyle\fP - which crystal to build 
.PD 0

.IP "\(bu" 2
\fCh-BN\fP or \fCMDC 2H/1T\fP or \fCTMDC 2H/1T\fP or \fCPETN-I\fP or \fCTATB\fP or \fCβ-HMX\fP 
.PP
.br
\fIbasisAtoms\fP - total number of basis atoms used for building graphene, 
.PD 0

.IP "\(bu" 2
2 or 4 
.PP
.br
\fIi_alat\fP - \fCa\fP lattice parameter 
.br
\fIi_clat\fP - \fCc\fP lattice parameter 
.br
\fIelements\fP - list of element symbols 
.RE
.PP

.SS "StructureLib::~StructureLib ()"

.SH "Member Function Documentation"
.PP 
.SS "void StructureLib::graphene (double i_alat, double i_clat, int basisAtoms)\fC [private]\fP"

.PP
Constrct an hexagonal 2 atom unit cell or a 4 atom rectangular unit cell\&. 
.PP
.nf
       _________            _________________           ^                      
      /        /           |                 |          |                      
     /    o   /            |    o     o      |          |                      
    /  o     /             |                 |          |                      
   /________/              |o____________o___|          |------------> x         
       2                           4                                           

.fi
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIi_alat\fP - lattice parameter for \fCa\fP, Å 
.br
\fIi_clat\fP - \fCc\fP lattice parameter 
.br
\fIbasisAtoms\fP - 
.PD 0

.IP "\(bu" 2
\fB\fC2\fP\fP for hexagonal, 
.IP "\(bu" 2
\fB\fC4\fP\fP rectangular 
.PP
.RE
.PP

.SS "void StructureLib::h_bn ()\fC [private]\fP"

.PP
Define the basis atoms and lattice for hexagonal Boron Nitride\&. \fCa\fP = \fCb\fP = 2\&.505 Å, \fCc\fP = 12 Å 
.SS "void StructureLib::hmx ()\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single crystal of HMX\&. 
.SS "void StructureLib::mdc_1t (double i_alat, double i_clat, std::vector< std::string > elements)\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single layer of a metal dichalcogenide, 
.br
 i\&.e\&. (Pb,Sn)(S,Se,Te)2 in the 1T polytype\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi_alat\fP - \fCa\fP lattice parameter, assumed that \fCa\fP = \fCb\fP 
.br
\fIi_clat\fP - \fCc\fP lattice parameter 
.br
\fIelements\fP - list of element symbols 
.RE
.PP

.SS "void StructureLib::mdc_2h (double i_alat, double i_clat, std::vector< std::string > elements)\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single layer of a metal dichalcogenide, 
.br
 i\&.e\&. (Pb,Sn)(S,Se,Te)2 in the 2H polytype\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi_alat\fP - \fCa\fP lattice parameter, assumed that \fCa\fP = \fCb\fP 
.br
\fIi_clat\fP - \fCc\fP lattice parameter, 
.br
\fIelements\fP - list of element symbols 
.RE
.PP

.SS "void StructureLib::petn ()\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single crystal of PETN-I\&. \fCa\fP = \fCb\fP = 9\&.38 Å, \fCc\fP = 6\&.71 Å 
.SS "void StructureLib::tatb ()\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single crystal of TATB\&. \fCa\fP = \fCb\fP = \fCc\fP = 9\&.01 Å 
.SS "void StructureLib::tmdc_1t (double i_alat, double i_clat, std::vector< std::string > elements)\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single layer of a transition metal dichalcogenide, 
.br
 i\&.e\&. (Mo,W)(S,Se,Te)2 in the 1T polytype\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi_alat\fP - \fCa\fP lattice parameter, assumed that \fCa\fP = \fCb\fP 
.br
\fIi_clat\fP - \fCc\fP lattice parameter 
.br
\fIelements\fP - list of element symbols 
.RE
.PP

.SS "void StructureLib::tmdc_2h (double i_alat, double i_clat, std::vector< std::string > elements)\fC [private]\fP"

.PP
Define the basis atoms and lattice for a single layer of a transition metal dichalcogenide, 
.br
 i\&.e\&. (Mo,W)(S,Se,Te)2 in the 2H polytype\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi_alat\fP - \fCa\fP lattice parameter, assumed that \fCa\fP = \fCb\fP 
.br
\fIi_clat\fP - \fCc\fP lattice parameter 
.br
\fIelements\fP - list of element symbols 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "double StructureLib::cta\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
