.TH "Tetragonal" 3 "Sun Oct 4 2015" "Crystal Builder v 3.7.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetragonal \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "\fBPurpose:\fP "
.PP
.PP
.PP
.nf
/******************************************************************************\
/  Class to generate the basis atom positions, lattice vectors and lattice     \
/  parameters, for the Tetragonal Bravais lattice class.                       \
/  a = b != c, α = β = γ = 90.                                                 \
/  Within this class, there are 3 available cubic styles that can be generated \
/  Simple Cubic, Body Centered, Face Centered                                  \
/  * * Inherits from the LATTICE class                                         \
/                                                                              \ 
/******************************************************************************\
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Joseph M\&. Gonzalez
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1
.RE
.PP
\fBDate:\fP
.RS 4
Sep 13, 2015 19:16:20
.RE
.PP
\fBContact\fP 
.br
 jmgonza6@mail.usf.edu 
.PP
Inherits \fBLATTICE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTetragonal\fP (double i_alat, double i_clat, char i_lstyle[], char *i_element)"
.br
.ti -1c
.RI "\fB~Tetragonal\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBprimitive\fP ()"
.br
.ti -1c
.RI "void \fBBCC\fP ()"
.br
.ti -1c
.RI "void \fBFCC\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tetragonal::Tetragonal (double i_alat, double i_clat, char i_lstyle[], char * i_element)"

.SS "Tetragonal::~Tetragonal ()"

.SH "Member Function Documentation"
.PP 
.SS "void Tetragonal::BCC ()\fC [private]\fP"

.SS "void Tetragonal::FCC ()\fC [private]\fP"

.SS "void Tetragonal::primitive ()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Crystal Builder v 3\&.7\&.0 from the source code\&.
